In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6659, 6492, 7330, 609],
 [6659, 6492, 7330, 217],
 [6659, 325, 7330, 6919],
 [4821, 6265, 5117, 4496, 8237],
 [4821, 6265, 5117, 4496, 5159],
 [3340, 6659, 3773, 7330, 4967],
 [3007, 973, 6519, 4496]]

In [15]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6659 6492 7330  609]
 [   0    0    0    0 6659 6492 7330  217]
 [   0    0    0    0 6659  325 7330 6919]
 [   0    0    0 4821 6265 5117 4496 8237]
 [   0    0    0 4821 6265 5117 4496 5159]
 [   0    0    0 3340 6659 3773 7330 4967]
 [   0    0    0    0 3007  973 6519 4496]]


In [18]:
## feature representation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 168ms/step


array([[[ 0.00575424, -0.0231238 , -0.02527331,  0.04458009,
         -0.00059575,  0.02178237, -0.00075495, -0.02030555,
         -0.03695424, -0.01149147],
        [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009,
         -0.00059575,  0.02178237, -0.00075495, -0.02030555,
         -0.03695424, -0.01149147],
        [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009,
         -0.00059575,  0.02178237, -0.00075495, -0.02030555,
         -0.03695424, -0.01149147],
        [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009,
         -0.00059575,  0.02178237, -0.00075495, -0.02030555,
         -0.03695424, -0.01149147],
        [ 0.01823227, -0.00770815, -0.00308423, -0.01884623,
          0.04106886, -0.01040279,  0.03243333, -0.04693823,
          0.01940086, -0.01525732],
        [ 0.04177428, -0.02213847,  0.04746165, -0.03297577,
          0.00965835, -0.04176791, -0.00601082,  0.02472056,
         -0.00702635, -0.01172284],
        [-0.04210936, -0.00018418,  0.03181497, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 6659, 6492, 7330,  609])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[ 0.00575424, -0.0231238 , -0.02527331,  0.04458009, -0.00059575,
         0.02178237, -0.00075495, -0.02030555, -0.03695424, -0.01149147],
       [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009, -0.00059575,
         0.02178237, -0.00075495, -0.02030555, -0.03695424, -0.01149147],
       [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009, -0.00059575,
         0.02178237, -0.00075495, -0.02030555, -0.03695424, -0.01149147],
       [ 0.00575424, -0.0231238 , -0.02527331,  0.04458009, -0.00059575,
         0.02178237, -0.00075495, -0.02030555, -0.03695424, -0.01149147],
       [ 0.01823227, -0.00770815, -0.00308423, -0.01884623,  0.04106886,
        -0.01040279,  0.03243333, -0.04693823,  0.01940086, -0.01525732],
       [ 0.04177428, -0.02213847,  0.04746165, -0.03297577,  0.00965835,
        -0.04176791, -0.00601082,  0.02472056, -0.00702635, -0.01172284],
       [-0.04210936, -0.00018418,  0.03181497, -0.00271677,  0.00281171,
         0.00102967, -0.00709641,  0.02527112